### ISSUE TITLE
possible to overload existing relations at runtime?

### ISSUE THREAD

**Issue by jakedowns** [i-rocky/eloquent-dynamic-relation#2]
hi there, thanks for a great pattern!

so it works as expected for me if i'm adding a new relationship that wasn't ever present on the model.

but what i'm trying to do in my project is to overload a Model relationship at runtime if the request/app happens to be running in our test mode (not a unit test per-se, but more like hitting a certain url needs to trigger the relationship to load some different data)

i originally solved this by setting a $GLOBALS flag, and a conditional in the base model relationship method, but that's no bueno. 

if i try to use addDynamicRelation('existingRelationshipName',...) the hasDynamicRelation method is never called for that method name. i tried commenting out the bit that checks cache first, but to no avail.

any ideas? thanks!

NOTE: i thought about just adding an argument to the relationship to trigger the different mode, but it needs to be transparent at call-time. i.e. the controller / blade templates depending on it shouldn't need to know anything about test-mode vs. normal-mode

---

UPDATE: I _thought_ the setRelation method described here in Adam Wathan's "Stubbing Eloquent Relations for Faster Tests" might help: https://adamwathan.me/2016/08/04/stubbing-eloquent-relations-for-faster-tests/
however, it only works if you're using eager-loaded relations accessed via ->relationship (property, not method call)
however, the relationship i'm trying to overload is more of a "getter" that i need to pass an argument to, therefore I must call it as a method instead of using the memoized property shorthand. 

---

UPDATE 2: using `$this->user->setRelations([]);` i was able to get `hasDynamicRelation` calling for my custom relationship resolver method. however, once `getRelationshipFromMethod` is called, it calls the original method.

---

UPDATE 3: I ended up mixing your Trait with a solution posted here for a pre-invocation-hook https://stackoverflow.com/questions/16751703/class-method-pre-invocation-hooking

(Man, it would be nice if there was an equivalent of __call that fired before all methods on a class fired, not just missing ones.)
Still a bit hackier than i would like, but it beats creating a bunch of factories for data i already have.

```
--- mymodel.php
public function myCustomRelationship_real($myparameter)
{
    return $this->belongsToMany(...); /*etc*
}

public function __call($function, $args){
    if($function === "myCustomRelationship"){
        if(static::hasDynamicRelation($function)){
            return call_user_func_array(static::$dynamic_relations[$function], array_merge([$this],$args));
        }
        return $this->myCustomRelationship_real($args[0]);
    }
    return parent::__call($function,$args);
}

--- elsewhere.php

$this->my_model->addDynamicRelation(
            'myCustomRelationship',
            function($model)use($mock_relationship){
                return $mock_relationship;
            }
);
```

**Comment by i-rocky** [comment]
Sorry, I had been very busy on a project at office and didn't notice anything else out of that project.
The `__call` method will only be called if the called method does not exist so if it's already defined then you're out of luck here.
You could use proxy to check your method first then call the model method but that would make it an anti-pattern I guess since there is no such thing as pre-method call.

**Comment by i-rocky** [comment]
Just a wild thought. If you add the hard-coded relations in your model's boot method as dynamic relation, you can override them as your wish.
